import net from "net";
import tls from "tls";

type MailPayload = {
  subject: string;
  html: string;
  text: string;
  replyTo?: string;
};

type LeadPayload = {
  name: string;
  phone: string;
  email: string;
  service: string;
  doctor: string;
  message: string;
};

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export function buildLeadEmail(type: "Appointment" | "Contact", lead: LeadPayload) {
  const rows = [
    ["Name", lead.name],
    ["Phone", lead.phone],
    ["Email", lead.email || "Not provided"],
    ["Service", lead.service || "Not selected"],
    ["Preferred Doctor", lead.doctor || "Not selected"],
    ["Message", lead.message || "Not provided"]
  ];

  const subject = `Twacha ${type} Enquiry - ${lead.name}`;
  const htmlRows = rows.map(([label, value]) => `
    <tr>
      <td style="padding:10px 12px;border:1px solid #dbe7e4;font-weight:700;background:#f6fbf9;">${label}</td>
      <td style="padding:10px 12px;border:1px solid #dbe7e4;">${escapeHtml(value)}</td>
    </tr>
  `).join("");

  return {
    subject,
    text: rows.map(([label, value]) => `${label}: ${value}`).join("\n"),
    html: `
      <div style="font-family:Arial,sans-serif;color:#18252b;line-height:1.5;">
        <h2 style="margin:0 0 12px;color:#096f71;">New ${type} Enquiry</h2>
        <p>A new lead was submitted from the Twacha Clinic website.</p>
        <table style="border-collapse:collapse;width:100%;max-width:680px;">${htmlRows}</table>
        <p style="font-size:12px;color:#66757c;margin-top:18px;">This email was generated by the Twacha Clinic Next.js website.</p>
      </div>
    `
  };
}

function readLine(socket: net.Socket | tls.TLSSocket) {
  return new Promise<string>((resolve, reject) => {
    let buffer = "";
    const onData = (chunk: Buffer) => {
      buffer += chunk.toString("utf8");
      if (/\r?\n/.test(buffer) && /^\d{3}[ -]/m.test(buffer)) {
        socket.off("data", onData);
        resolve(buffer);
      }
    };
    socket.on("data", onData);
    socket.once("error", reject);
  });
}

async function command(socket: net.Socket | tls.TLSSocket, line: string) {
  socket.write(`${line}\r\n`);
  return readLine(socket);
}

function encodeAddress(name: string, email: string) {
  return `"${name.replaceAll('"', "")}" <${email}>`;
}

export async function sendMail(payload: MailPayload) {
  const host = process.env.SMTP_HOST;
  const port = Number(process.env.SMTP_PORT || 587);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  const to = process.env.MAIL_TO || process.env.SMTP_TO;
  const from = process.env.SMTP_FROM || user;
  const secure = process.env.SMTP_SECURE === "true" || port === 465;

  if (!host || !user || !pass || !to || !from) {
    return { sent: false, reason: "SMTP is not configured" };
  }

  const socket = secure
    ? tls.connect({ host, port, servername: host })
    : net.connect({ host, port });

  await new Promise<void>((resolve, reject) => {
    socket.once("connect", resolve);
    socket.once("secureConnect", resolve);
    socket.once("error", reject);
  });

  await readLine(socket);
  await command(socket, `EHLO ${host}`);

  let activeSocket: net.Socket | tls.TLSSocket = socket;
  if (!secure && port === 587) {
    await command(activeSocket, "STARTTLS");
    activeSocket = tls.connect({ socket, servername: host });
    await new Promise<void>((resolve, reject) => {
      activeSocket.once("secureConnect", resolve);
      activeSocket.once("error", reject);
    });
    await command(activeSocket, `EHLO ${host}`);
  }

  await command(activeSocket, "AUTH LOGIN");
  await command(activeSocket, Buffer.from(user).toString("base64"));
  await command(activeSocket, Buffer.from(pass).toString("base64"));
  await command(activeSocket, `MAIL FROM:<${from}>`);
  await command(activeSocket, `RCPT TO:<${to}>`);
  await command(activeSocket, "DATA");

  const headers = [
    `From: ${encodeAddress("Twacha Website", from)}`,
    `To: ${to}`,
    `Subject: ${payload.subject}`,
    payload.replyTo ? `Reply-To: ${payload.replyTo}` : "",
    "MIME-Version: 1.0",
    "Content-Type: text/html; charset=UTF-8"
  ].filter(Boolean).join("\r\n");

  activeSocket.write(`${headers}\r\n\r\n${payload.html}\r\n.\r\n`);
  await readLine(activeSocket);
  await command(activeSocket, "QUIT");
  activeSocket.end();
  return { sent: true };
}
